plugins:
    JDBCTransport:
        classpath: ${jdbc.connectivityPluginDir}/connectivity-jdbc.jar
        class: com.apama.adbc.JDBCTransport
    mapperCodec:
        libraryName: MapperCodec
        class: MapperCodec
    diagnosticCodec:
        libraryName: DiagnosticCodec
        class: DiagnosticCodec

startChains:
    # Each JDBC chain provides a single JDBC connection, and so allows one statement to be executed at a time


    # NB: this is the main chain used in the 2020Oct IW
    JDBC:
        - apama.eventMap:
            allowMissing: true
        - diagnosticCodec
        - JDBCTransport:
            autoCommit: true
            jdbcURL: ${jdbc.url}
            jdbcUser: ${jdbc.user}
            jdbcPassword: ${jdbc.password}

    # Chains from previous IWs
    storeEvents:
        - apama.eventMap:
        - mapperCodec:
            "*":
                towardsTransport:
                    mapFrom:
                        - payload.row: payload
                        - payload.row._apama_type: metadata.sag.type
                    defaultValue:
                        - payload.messageId: -1
                        - payload.smallResultSet: false
                        - payload.maxSmallQuerySize: -1                        
                        - metadata.sag.type: "com.apama.adbc.Store"
                        - payload.tableName: "StoredEvents"
        - JDBCTransport:
            jdbcURL: ${jdbc.url}
            jdbcUser: ${jdbc.user}
            jdbcPassword: ${jdbc.password}

    recoverEvents:
        - apama.eventMap:
            allowMissing: true
        - mapperCodec:
            "com.apama.adbc.ResultEvent":
                towardsHost:
                    mapFrom:
                        - metadata.sag.type: payload.row._apama_type
                        - payload: payload.row
        - JDBCTransport:
            jdbcURL: ${jdbc.url}
            jdbcUser: ${jdbc.user}
            jdbcPassword: ${jdbc.password}
            


